version: '3.8'
services:
  app:
    build: .
    image: my-camunda-challenge-app:latest
    ports:
      - "8080:8080"
    volumes:
      - animaldb-data:/app/data
    environment:
      - DB_URL=jdbc:h2:file:/app/data/animaldb
volumes:
  animaldb-data: